test_data = [{'asin': 'B07WHSY2WT', 'url': 'http://www.amazon.de/dp/B07WHSY2WT',
              'title': 'PlayStation 4 Slim - Konsole (1 TB, schwarz) inkl. FIFA 20 + 2 DualShock Controller',
              'seller': 'Sony Interactive Entertainment', 'price': 379.0},
             {'asin': 'B085PB4B6J', 'url': 'http://www.amazon.de/dp/B085PB4B6J',
              'title': 'PlayStation 4 Pro - Konsole (1 TB, schwarz) PS Hits Naughty Dog Bundle',
              'seller': 'Sony Interactive Entertainment', 'price': 399.99},
             {'asin': 'B07HHPX4N1', 'url': 'http://www.amazon.de/dp/B07HHPX4N1',
              'title': 'PlayStation 4 - Konsole (500 GB, schwarz, slim, F-Chassis) inkl. 2 DualShock 4 Controller',
              'seller': 'Sony Interactive Entertainment', 'price': 299.99},
             {'asin': 'B07HSJW7HK', 'url': 'http://www.amazon.de/dp/B07HSJW7HK',
              'title': 'PlayStation 4 Pro - Konsole (1 TB, schwarz, Pro, Modell: CUH-7216B)',
              'seller': 'Sony Interactive Entertainment', 'price': 408.0},
             {'asin': 'B07KMV94JF', 'url': 'http://www.amazon.de/dp/B07KMV94JF',
              'title': 'PlayStation 4 Slim - Konsole (1TB, schwarz)', 'seller': 'Sony Interactive Entertainment',
              'price': 359.0}, {'asin': 'B07HNR4ZZD', 'url': 'http://www.amazon.de/dp/B07HNR4ZZD',
                                'title': 'PlayStation4 - Konsole (500GB, schwarz, slim)', 'seller': 'Sony',
                                'price': 317.0}, {'asin': 'B07V7NT6ZC', 'url': 'http://www.amazon.de/dp/B07V7NT6ZC',
                                                  'title': 'PlayStation 4 Pro (1TB, black): Fortnite Neo Versa Bundle',
                                                  'seller': 'Sony', 'price': 409.98},
             {'asin': 'B07V282WBB', 'url': 'http://www.amazon.de/dp/B07V282WBB',
              'title': 'PlayStation 4 Slim - Konsole (500GB, Jet Black) + 2 Controller: Fortnite Neo Versa Bundle',
              'seller': 'Sony', 'price': 369.0}, {'asin': 'B07YGJGFZC', 'url': 'http://www.amazon.de/dp/B07YGJGFZC',
                                                  'title': 'PlayStation 4 Virtual Reality Megapack - Edition 2 (inkl. Skyrim, Astro Bot Rescue Mission, VR Worlds, Resident Evil: Biohazard, Everybody´s Golf)',
                                                  'seller': 'Sony Interactive Entertainment', 'price': 379.0},
             {'asin': 'B07K2PT733', 'url': 'http://www.amazon.de/dp/B07K2PT733', 'title': 'PlayStation VR',
              'seller': 'Sony Interactive Entertainment', 'price': 289.0},
             {'asin': 'B07Z7438CY', 'url': 'http://www.amazon.de/dp/B07Z7438CY',
              'title': 'Spongebob SquarePants: Battle for Bikini Bottom - Rehydrated - F.U.N. Edition [Playstation 4]',
              'seller': 'THQ Nordic', 'price': 299.99},
             {'asin': 'B07DNM3MT9', 'url': 'http://www.amazon.de/dp/B07DNM3MT9',
              'title': 'PlayStation 4 Pro - Konsole Schwarz, A Chassis, 1TB, (Generalüberholt)',
              'seller': 'Sony Interactive Entertainment', 'price': 349.99},
             {'asin': 'B07WDKT7DP', 'url': 'http://www.amazon.de/dp/B07WDKT7DP',
              'title': 'PlayStation 4 Pro - Konsole (1TB) inkl. FIFA 20',
              'seller': 'Sony Interactive Entertainment', 'price': 419.0},
             {'asin': 'B07YSX4DLW', 'url': 'http://www.amazon.de/dp/B07YSX4DLW',
              'title': 'PlayStation 4 Slim inkl. 2 Controller und Call of Duty: Modern Warfare - Konsolenbundle (1TB, schwarz, Slim)',
              'seller': 'Sony', 'price': 444.0}, {'asin': 'B07S7RGRFC', 'url': 'http://www.amazon.de/dp/B07S7RGRFC',
                                                  'title': 'Playstation 4 Slim 1TB - Limited Edition Days of Play 2019',
                                                  'seller': 'Sony', 'price': 359.0},
             ]
